name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./days_until_christmas_for_macos
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./days_until_christmas_for_macos
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Days until Christmas (MacOS)
        path: |
          days_until_christmas_for_macos/target/debug/days_until_christmas
